# Generated by Django 5.2 on 2025-04-10 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='baho',
            name='oquvchi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baholar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baho',
            name='fan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baholar', to='grade.fan'),
        ),
        migrations.AddField(
            model_name='sinf',
            name='oquvchi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fan',
            name='sinf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.sinf'),
        ),
    ]
