# Generated by Django 5.2 on 2025-04-12 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinf',
            name='oquvchi',
        ),
        migrations.AddField(
            model_name='sinf',
            name='oquvchi',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
